### PR TITLE
Update license to 2-clause BSD in most places

### LINKED ISSUE #20: Release under the same license as EditorConfig Core
The current Python Software Foundation license is [not suitable for third-party works](https://wiki.python.org/moin/PythonSoftwareFoundationLicenseFaq#How_do_I_use_the_PSF_License.3F); neither is it suitable for contributing code to the Python Software Foundation.

Please change all the license grants to be the same as for the rest of EditorConfig Core; I think that would be [the “BSD 2-clause” license](https://spdx.org/licenses/BSD-2-Clause.html). Then, make a new release to PyPI with that license declared in the metadata.

### PR DESCRIPTION
**Pull request by treyhunner**
Closes #20.

### CODE REVIEW

**Comment by treyhunner** [comment]
Feel free to @xuhdev merge if you feel this is suitable

**Comment by xuhdev** [comment]
I like the overall change, but I feel the two different copyright notices should be consistent... And do we need to say "all right reserved"? It seems like no one in the world no longer need to add that.

**Comment by treyhunner** [comment]
Good point. I just updated it and will merge soon. Thanks!

**Comment by xuhdev** [comment]
@treyhunner Thanks! Can you add `(c)` after the word "Copyright"? I think it might be more appropriate for you to do it since you made the last relevant change...

**Pull request merged**
